Repository PumpMyKins/PMK-BungeeUtils, pull requests merged in 2018-10, with the labels that each got.

#9 Feature/add hotbarconnect v3
  .settings/org.eclipse.core.resources.prefs
  pom.xml
  src/main/java/fr/pmk_bungeeutils/MainBungeeUtils.java
  src/main/java/fr/pmk_bungeeutils/autobroadcast/AutoBroadcastManager.java
  src/main/java/fr/pmk_bungeeutils/commands/BroadcastAll.java
  src/main/java/fr/pmk_bungeeutils/hotbarconnect/HotBarConnectManager.java
  src/main/java/fr/pmk_bungeeutils/hotbarconnect/data/HbcServer.java
  src/main/java/fr/pmk_bungeeutils/network/MessagingListener.java
  src/main/java/fr/pmk_bungeeutils/network/PluginMessagingManager.java
Labels: feature

#5 Ajout /msg inter-serveurs
  src/main/java/fr/pmk_bungeeutils/MainBungeeUtils.java
  src/main/java/fr/pmk_bungeeutils/commands/MessageServer.java
  src/main/java/fr/pmk_bungeeutils/pmkbuy/BuyInfoCommand.java
Labels: feature, waiting-test

#10 Develop vers Master
  src/main/java/fr/pmk_bungeeutils/MainBungeeUtils.java
  src/main/java/fr/pmk_bungeeutils/commands/MessageServer.java
  src/main/java/fr/pmk_bungeeutils/pmkbuy/BuyInfoCommand.java
Labels: feature, hotfix

#12 Hotfix/msg command
  src/main/java/fr/pmk_bungeeutils/commands/MessageServer.java
Labels: feature

#13 Hotfix/msg command
  src/main/java/fr/pmk_bungeeutils/commands/MessageServer.java
Labels: hotfix

#14 Fix support cmd serveur display onExecute
  src/main/java/fr/pmk_bungeeutils/support/SupportCommand.java
Labels: hotfix

#15 Hotfix/msg command
  src/main/java/fr/pmk_bungeeutils/commands/MessageServer.java
Labels: hotfix

#16 Ajout complétion grace au tab
  src/main/java/fr/pmk_bungeeutils/commands/MessageServer.java
Labels: feature

#17 Hotfix/msg command
  src/main/java/fr/pmk_bungeeutils/commands/MessageServer.java
Labels: hotfix
